### ISSUE TITLE
get make errors when installing argos3 via homebrew  

### ISSUE THREAD

**Issue by Hongliupb** [ilpincy/homebrew-argos3#1]
Hi Carlo,

When i tried to install argos3 via homwbrew. I get following error, maybe you can help?

 brew install argos3
==> Downloading https://github.com/ilpincy/argos3/archive/3.0.0-beta28.tar.gz
Already downloaded: /Library/Caches/Homebrew/argos3-3.0.0-beta28.tar.gz
==> cmake ../src -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/Ce
==> make
[ 45%] Building CXX object plugins/simulator/physics_engines/dynamics2d/CMakeFiles/argos3plugin_simulator_dynamics2d.dir/dynamics2d_gripping.cpp.o
[ 45%] Building CXX object plugins/simulator/physics_engines/dynamics2d/CMakeFiles/argos3plugin_simulator_dynamics2d.dir/dynamics2d_velocity_control.cpp.o
Linking CXX shared library libargos3plugin_simulator_dynamics2d.dylib
[ 45%] Built target argos3plugin_simulator_dynamics2d
make: **\* [all] Error 2

**Comment by ilpincy** [comment]
Hi Hongli,

I tried to reproduce the problem on my Mac, but it works fine. Could you please give me some more detail?
1. Which MacOS version are you using?
2. Could you please copy/paste the entire compilation output, so that the exact error is present?

Thanks in advance!
Carlo

**Comment by Hongliupb** [comment]
Hi carlo,

I am using macos 10.9.4

all erros i get from brew is what i send you. But i also tried to compile argos directly. I get errors as following:
Lua is already installed on my system. I also re installed Lua lib. it gives the same error.

Thanks very much,

—Hongli 

[ hongliding air-de-hongli ~/Documents/argos3/build ] make
[ 21%] Built target argos3core_simulator
[ 22%] Built target argos3
[ 23%] Built target argos3plugin_simulator_media
[ 30%] Built target argos3plugin_simulator_entities
[ 30%] Building CXX object plugins/robots/generic/CMakeFiles/argos3plugin_simulator_genericrobot.dir/control_interface/ci_colored_blob_omnidirectional_camera_sensor.cpp.o
/Users/hongliding/Documents/argos3/src/plugins/robots/generic/control_interface/ci_colored_blob_omnidirectional_camera_sensor.cpp:59:30: error: 
      use of undeclared identifier 'lua_objlen'
      size_t unLastBlobNum = lua_objlen(pt_lua_state, -1);
                             ^
1 error generated.
make[2]: **\* [plugins/robots/generic/CMakeFiles/argos3plugin_simulator_genericrobot.dir/control_interface/ci_colored_blob_omnidirectional_camera_sensor.cpp.o] Error 1
make[1]: **\* [plugins/robots/generic/CMakeFiles/argos3plugin_simulator_genericrobot.dir/all] Error 2
make: **\* [all] Error 2

**Comment by ilpincy** [comment]
Hi Hongli,

The problem is due to a recent change in HomeBrew. They made lua5.2 the default, but ARGoS uses lua5.1. To fix the problem, proceed as follows:
1. Uninstall all the versions of lua you have now:
   $ brew uninstall lua lua5.1 lua5.2
2. Make sure there's no lua package installed anymore. This command must return nothing:
   $ brew list | grep lua
3. Install ARGoS:
   $ brew install argos3

This should fix your problem. Let me know!

Cheers,
Carlo

**Comment by Hongliupb** [comment]
HI, Ii just moved away lua5.1 and the installation works. now new problem is can not run argos. errors are here:
[ hongliding air-de-hongli ~/Documents/argos3/src/testing/experiment ] argos3 -c test_footbot.xml
[INFO] Not using threads
[INFO] Using random seed = 12345
[INFO] Using simulation clock tick = 0.1
[INFO] Total experiment length in clock ticks = 6000
[FATAL] Error initializing loop functions
[FATAL] Symbol "test_lf" not found

thanks for your help,
Cheers,
--Hongli

**Comment by ilpincy** [comment]
Hi Hongli,

Don't use the tests in the ARGoS sources - they are for me only. Use the examples here: github.com/ilpincy/argos3-examples.

Cheers,
Carlo

**Comment by avardy** [comment]
I think I am having a similar issue installing argos3 on a Mac.  When I do "brew install argos3" it always seems to use Lua 5.2.  I can uninstall 5.2 and install 5.1, but argos3 seems to list "lua" as a dependency not "lua51".  Here's the result:

bodhran:~ av$ brew install argos3
==> Installing argos3 from ilpincy/homebrew-argos3
==> Installing argos3 dependency: lua
==> Downloading https://homebrew.bintray.com/bottles/lua-5.2.3_1.mountain_lion.b
Already downloaded: /Library/Caches/Homebrew/lua-5.2.3_1.mountain_lion.bottle.tar.gz
==> Pouring lua-5.2.3_1.mountain_lion.bottle.tar.gz
🍺  /usr/local/Cellar/lua/5.2.3_1: 13 files, 332K
==> Installing argos3
==> Downloading https://github.com/ilpincy/argos3/archive/3.0.0-beta30.tar.gz
Already downloaded: /Library/Caches/Homebrew/argos3-3.0.0-beta30.tar.gz
==> cmake ../src -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/Ce
==> make
[ 22%] Building CXX object core/CMakeFiles/argos3core_simulator.dir/wrappers/lua/lua_controller.cpp.o
[ 22%] Building CXX object core/CMakeFiles/argos3core_simulator.dir/wrappers/lua/lua_utility.cpp.o
Linking CXX shared library libargos3core_simulator.dylib
[ 22%] Built target argos3core_simulator
make: **\* [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ilpincy/homebrew-argos3/issues

**Comment by ilpincy** [comment]
Hi avardy,

Could you please attach the build log of HomeBrew? The output you provided does not offer much information. You find the build log in ~/Library/Logs/Homebrew/argos3.

Cheers,
Carlo

**Comment by avardy** [comment]
Thanks for getting back to me!  I wasn't sure what files would be of 
interest so I've zipped up and attached the full contents of 
~/Library/Logs/Homebrew/argos3.

Hope the answer lies within!  Best...
Andrew

On 2015-03-18 9:42 PM, Carlo Pinciroli wrote:

> Hi avardy,
> 
> Could you please attach the build log of HomeBrew? The output you 
> provided does not offer much information. You find the build log in 
> ~/Library/Logs/Homebrew/argos3.
> 
> Cheers,
> Carlo
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ilpincy/homebrew-argos3/issues/1#issuecomment-83231073.

## 

Andrew Vardy, Ph.D, P.Eng
Associate Professor
Computer Science / Electrical and Computer Engineering
Memorial University of Newfoundland, St. John's, Canada
http://www.cs.mun.ca/~av/

**Comment by ilpincy** [comment]
Hi Andrew,

I can't find the attachment. :-) 

Cheers,
Carlo

**Comment by avardy** [comment]
Oh dear...  Actually, I did send it but maybe github doesn't like 
attachments.  Here is my directory listing.  What file(s) would be useful?

n033h102:argos3 av$ ll
total 352
-rw-r--r--  1 av  staff  23084 18 Mar 21:32 01.cmake.cc
-rw-r--r--  1 av  staff   2245 18 Mar 21:32 01.cmake
-rw-r--r--  1 av  staff  67525 18 Mar 21:33 CMakeCache.txt
-rw-r--r--  1 av  staff  73043 18 Mar 21:33 02.make.cc
-rw-r--r--  1 av  staff   6855 18 Mar 21:33 02.make

Thanks,
Andrew

On 2015-03-19 1:12 PM, Carlo Pinciroli wrote:

> Hi Andrew,
> 
> I can't find the attachment. :-)
> 
> Cheers,
> Carlo
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ilpincy/homebrew-argos3/issues/1#issuecomment-83639033.

## 

Andrew Vardy, Ph.D, P.Eng
Associate Professor
Computer Science / Electrical and Computer Engineering
Memorial University of Newfoundland, St. John's, Canada
http://www.cs.mun.ca/~av/

**Comment by ilpincy** [comment]
Send them to my personal email. The files 02\* are those I need.

I checked on two Macs (one with Yosemite and one with Mavericks) and it's
weird you have compilation issues. Everything works for me. Try the
following commands:

Uninstall any version that could have been previously present
$ brew uninstall argos3

Uninstall manually installed code (if you tried argos from the sources)
$ sudo /usr/local/share/argos3/uninstall_argos3.sh

Uninstall conflicting versions of lua
$ brew uninstall lua lua51

Update homebrew to the latest version
$ brew update

Install lua and argos3
$ brew install lua argos3

Cheers,
Carlo

On Thu, Mar 19, 2015 at 2:38 PM, avardy notifications@github.com wrote:

> Oh dear... Actually, I did send it but maybe github doesn't like
> attachments. Here is my directory listing. What file(s) would be useful?
> 
> n033h102:argos3 av$ ll
> total 352
> -rw-r--r-- 1 av staff 23084 18 Mar 21:32 01.cmake.cc
> -rw-r--r-- 1 av staff 2245 18 Mar 21:32 01.cmake
> -rw-r--r-- 1 av staff 67525 18 Mar 21:33 CMakeCache.txt
> -rw-r--r-- 1 av staff 73043 18 Mar 21:33 02.make.cc
> -rw-r--r-- 1 av staff 6855 18 Mar 21:33 02.make
> 
> Thanks,
> Andrew
> 
> On 2015-03-19 1:12 PM, Carlo Pinciroli wrote:
> 
> > Hi Andrew,
> > 
> > I can't find the attachment. :-)
> > 
> > Cheers,
> > Carlo
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ilpincy/homebrew-argos3/issues/1#issuecomment-83639033
> > .
> 
> ## 
> 
> Andrew Vardy, Ph.D, P.Eng
> Associate Professor
> Computer Science / Electrical and Computer Engineering
> Memorial University of Newfoundland, St. John's, Canada
> http://www.cs.mun.ca/~av/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ilpincy/homebrew-argos3/issues/1#issuecomment-83709876
> .

## 

Carlo Pinciroli, Ph.D.
http://carlo.pinciroli.net/

**Comment by tilly111** [comment]
> Hi Hongli,
> 
> The problem is due to a recent change in HomeBrew. They made lua5.2 the default, but ARGoS uses lua5.1. To fix the problem, proceed as follows:
> 
> 1. Uninstall all the versions of lua you have now:
>    $ brew uninstall lua lua5.1 lua5.2
> 2. Make sure there's no lua package installed anymore. This command must return nothing:
>    $ brew list | grep lua
> 3. Install ARGoS:
>    $ brew install argos3
> 
> This should fix your problem. Let me know!
> 
> Cheers,
> Carlo

Hi,
i have the same problem. I did this and if i brew install argos3 it always reinstalls lua5.3 is there any way to surpress this?

Kind regards
Till

**Comment by ilpincy** [comment]
I made Lua non-required, so you can build again. I also fixed the main ARGoS script that checks for Lua so it ignores 5.3 if it's installed. I'll make a new release this weekend so normal the installation process works again. Thank you for spotting this problem!

**Comment by tilly111** [comment]
Much thanks.

**Comment by tilly111** [comment]
Hi, 
it's me again. I still have this problem. When I try to install argos3 it automatically downloads and installs lua5.3 even if lua5.1 is already installed. (enclosed the error code if I try to make):

Last 15 lines from /Users/[my Name]/Library/Logs/Homebrew/argos3/02.make:
using ::isunordered;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
[  4%] Building CXX object core/CMakeFiles/argos3core_simulator.dir/utility/profiler/profiler.cpp.o
13 errors generated.
make[2]: *** [core/CMakeFiles/argos3core_simulator.dir/utility/signal_processing.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
13 errors generated.
make[2]: *** [core/CMakeFiles/argos3core_simulator.dir/utility/datatypes/byte_array.cpp.o] Error 1
13 errors generated.
make[2]: *** [core/CMakeFiles/argos3core_simulator.dir/utility/rate.cpp.o] Error 1
make[1]: *** [core/CMakeFiles/argos3core_simulator.dir/all] Error 2
make: *** [all] Error 2

**Comment by ilpincy** [comment]
The error you reported does not seem to be related to Lua. I just tried to install ARGoS in Catalina and everything worked. Can you give me some details on your OS?

**Comment by tilly111** [comment]
macOS Catalina 10.15.1

**Comment by ilpincy** [comment]
Did you update HomeBrew? And what is the version of XCode you're using? Is it the latest version?

**Comment by tilly111** [comment]
HomeBrew is updated and XCode is the newest version 11.2.1 .

**Comment by tilly111** [comment]
What worked for me was downloading the git repository and compiling it manually. Though i had to install some extra libraries and change the makefiles from lua 5.2 required to just lua (but make sure u only have lua 5.2).

**Comment by ilpincy** [comment]
I don't understand. The latest release of ARGoS right now is literally the same as the git HEAD. Also, Lua is not required and the check is correct. I'm not sure which procedure you followed originally, but there is something wrong in what you did that I can't guess with the information you provided me. There is no need to change anything in ARGoS as it stands, to the best of my understanding and from the tests I conducted on 3 different Mac computers.
