### ISSUE TITLE
errors when installing argos3 via homebrew

### ISSUE THREAD

**Issue by Antonio-Griego** [ilpincy/homebrew-argos3#2]
Hello Carlo,

I was recently trying to install argos3 via homebrew and I ran into some problems with the installation. There appears to be compilation errors after homebrew downloads the most recent version of argos. I had installed argos on my Mac months ago with the previous release with no problems. Back then, both my OS version and the argos version (beta 28) was different than now.

Currently:
1. My OS version is 10.10.2 (OX X Yosemite)
2. the installation log with errors follows:

---

==> Installing argos3 from ilpincy/homebrew-argos3
==> Downloading https://github.com/ilpincy/argos3/archive/3.0.0-beta29.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-481; Mac OS X 10.10.2) https://github.com/ilpincy/argos3/archive/3.0.0-beta29.tar.gz -C 0 -o /Library/Caches/Homebrew/argos3-3.0.0-beta29.tar.gz.incomplete --silent
==> Verifying argos3-3.0.0-beta29.tar.gz checksum
tar xf /Library/Caches/Homebrew/argos3-3.0.0-beta29.tar.gz
==> cmake ../src -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/argos3/3.0.0-beta29 -DARGOS_BUILD_NATIVE=ON
-- The C compiler identification is AppleClang 6.0.0.6000056
-- The CXX compiler identification is AppleClang 6.0.0.6000056
-- Check for working C compiler: /usr/local/Library/ENV/4.3/clang
-- Check for working C compiler: /usr/local/Library/ENV/4.3/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- GCC/G++ version >= 4.2.1
-- Found DLFCN: /usr/lib/libdl.dylib  
-- Found Pthreads: /usr/lib/libpthread.dylib  
-- GSL using gsl-config /usr/local/bin/gsl-config
-- Using GSL from /usr/local/Cellar/gsl/1.16
-- Could NOT find GooglePerfTools (missing:  GOOGLEPERFTOOLS_LIBRARY GOOGLEPERFTOOLS_INCLUDE_DIR) 
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.9.1") 
-- Found ASCIIDoc: /usr/local/bin/asciidoc  
-- Found Lua51: /usr/local/lib/liblua5.1.dylib  
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - not found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - found
-- Looking for QT_MAC_USE_COCOA
-- Looking for QT_MAC_USE_COCOA - found
-- Found Qt4: /usr/local/bin/qmake (found version "4.8.6") 
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework  
-- Found GLUT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/GLUT.framework  
-- Configuring done
CMake Warning (dev) at plugins/simulator/visualizations/qt-opengl/CMakeLists.txt:91 (add_library):
  Policy CMP0038 is not set: Targets may not link directly to themselves.
  Run "cmake --help-policy CMP0038" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Target "argos3plugin_simulator_qtopengl" links to itself.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at plugins/simulator/visualizations/qt-opengl/CMakeLists.txt:91 (add_library):
  Policy CMP0038 is not set: Targets may not link directly to themselves.
  Run "cmake --help-policy CMP0038" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Target "argos3plugin_simulator_qtopengl" links to itself.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   argos3core_simulator
   argos3plugin_simulator_actuators
   argos3plugin_simulator_dynamics2d
   argos3plugin_simulator_entities
   argos3plugin_simulator_epuck
   argos3plugin_simulator_footbot
   argos3plugin_simulator_genericrobot
   argos3plugin_simulator_media
   argos3plugin_simulator_qtopengl
   argos3plugin_simulator_sensors

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /tmp/argos3-uKMSQn/argos3-3.0.0-beta29/build_simulator
==> make
Scanning dependencies of target test-list
[  1%] Building CXX object testing/CMakeFiles/test-list.dir/unit/test-list.cpp.o
Scanning dependencies of target argos3core_simulator
[  1%] [  2%] [  2%] Building CXX object core/CMakeFiles/argos3core_simulator.dir/utility/configuration/command_line_arg_parser.cpp.o
Building CXX object core/CMakeFiles/argos3core_simulator.dir/utility/string_utilities.cpp.o
Building CXX object core/CMakeFiles/argos3core_simulator.dir/utility/configuration/tinyxml/ticpp.cpp.o
Linking CXX executable test-list
[  2%] Built target test-list
[  3%] Building CXX object core/CMakeFiles/argos3core_simulator.dir/utility/configuration/tinyxml/tinystr.cpp.o
[  3%] Building CXX object core/CMakeFiles/argos3core_simulator.dir/utility/configuration/tinyxml/tinyxml.cpp.o
[  4%] Building CXX object core/CMakeFiles/argos3core_simulator.dir/utility/configuration/tinyxml/tinyxmlerror.cpp.o
[  4%] Building CXX object core/CMakeFiles/argos3core_simulator.dir/utility/configuration/tinyxml/tinyxmlparser.cpp.o
[  5%] Building CXX object core/CMakeFiles/argos3core_simulator.dir/utility/datatypes/byte_array.cpp.o
[  5%] Building CXX object core/CMakeFiles/argos3core_simulator.dir/utility/datatypes/color.cpp.o
/tmp/argos3-uKMSQn/argos3-3.0.0-beta29/src/core/utility/datatypes/byte_array.cpp:26:18: error: expected ')'
   static UInt64 htonll(UInt64 un_value) {
                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
# define htonll(x)       __DARWIN_OSSwapInt64(x)

```
                    ^
```

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
/tmp/argos3-uKMSQn/argos3-3.0.0-beta29/src/core/utility/datatypes/byte_array.cpp:26:18: note: to match this '('
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
# define htonll(x)       __DARWIN_OSSwapInt64(x)

```
                    ^
```

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
/tmp/argos3-uKMSQn/argos3-3.0.0-beta29/src/core/utility/datatypes/byte_array.cpp:42:18: error: expected ')'
   static UInt64 ntohll(UInt64 un_value) {
                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
# define ntohll(x)       __DARWIN_OSSwapInt64(x)

```
                    ^
```

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
/tmp/argos3-uKMSQn/argos3-3.0.0-beta29/src/core/utility/datatypes/byte_array.cpp:42:18: note: to match this '('
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
# define ntohll(x)       __DARWIN_OSSwapInt64(x)

```
                    ^
```

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
/tmp/argos3-uKMSQn/argos3-3.0.0-beta29/src/core/utility/datatypes/byte_array.cpp:42:18: error: redefinition of '__builtin_constant_p'
   static UInt64 ntohll(UInt64 un_value) {
                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
# define ntohll(x)       __DARWIN_OSSwapInt64(x)

```
                    ^
```

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
/tmp/argos3-uKMSQn/argos3-3.0.0-beta29/src/core/utility/datatypes/byte_array.cpp:26:18: note: previous definition is here
   static UInt64 htonll(UInt64 un_value) {
                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
# define htonll(x)       __DARWIN_OSSwapInt64(x)

```
                    ^
```

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
3 errors generated.
make[2]: **\* [core/CMakeFiles/argos3core_simulator.dir/utility/datatypes/byte_array.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[1]: **\* [core/CMakeFiles/argos3core_simulator.dir/all] Error 2
make: **\* [all] Error 2
==> Formula
Tap: ilpincy/homebrew-argos3
Path: /usr/local/Library/Taps/ilpincy/homebrew-argos3/argos3.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: b42c5c0b2112afe19a2d88d4d7b0d836852e47da
Last commit: 36 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit sandybridge
OS X: 10.10.2-x86_64
Xcode: 6.1.1
CLT: N/A
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.7.0_51
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/qt/Frameworks:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/graphviz/lib/pkgconfig:/usr/local/opt/gsl/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/lua51/lib/pkgconfig:/usr/local/opt/qt/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/pkg-config/bin:/usr/local/opt/cmake/bin:/usr/local/opt/asciidoc/bin:/usr/local/opt/graphviz/bin:/usr/local/opt/doxygen/bin:/usr/local/opt/gsl/bin:/usr/local/opt/libpng/bin:/usr/local/opt/lua51/bin:/usr/local/opt/qt/bin:/usr/bin:/bin:/usr/sbin:/sbin

Logs:
     /Users/deano505x/Library/Logs/Homebrew/argos3/01.cmake
     /Users/deano505x/Library/Logs/Homebrew/argos3/01.cmake.cc
     /Users/deano505x/Library/Logs/Homebrew/argos3/02.make
     /Users/deano505x/Library/Logs/Homebrew/argos3/02.make.cc
     /Users/deano505x/Library/Logs/Homebrew/argos3/CMakeCache.txt

**Comment by ilpincy** [comment]
Hi Antonio,

Thanks for the bug report!

I made a new release of ARGoS (beta30) with lots of new stuff (+ this issue fixed) and updated the HomeBrew script.

The new version of ARGoS wants Lua 5.2 installed, not 5.1. So, do the following:

``` bash
# Update the homebrew repository
$ brew update
# Uninstall Lua 5.1
$ brew uninstall lua51
# Install Lua 5.2 and argos3
$ brew install lua argos3
```

I won't close this issue until you confirm that the installation goes through. My Mac OS is one version behind yours, so I don't have the possibility to check everything. I'll have a new Mac to play with only next month :-)

Thanks!
Carlo

**Comment by Antonio-Griego** [comment]
Thank you very much for your assistance.

I am able to get argos3 installed and running on my mac now with very few problems. There was one issue where argos3 was not being properly linked and I had to change read/write permissions in the argos install directory in order for brew to be able to link it (even with override). Otherwise, the new version works well.

Much appreciated!
—Antonio Griego

On Feb 27, 2015, at 10:51 AM, Carlo Pinciroli <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Antonio,

Thanks for the bug report!

I made a new release of ARGoS (beta30) with lots of new stuff (+ this issue fixed) and updated the HomeBrew script.

The new version of ARGoS wants Lua 5.2 installed, not 5.1. So, do the following:

# Update the homebrew repository

$ brew update

# Uninstall Lua 5.1

$ brew uninstall lua51

# Install Lua 5.2 and argos3

$ brew install lua argos3

I won't close this issue until you confirm that the installation goes through. My Mac OS is one version behind yours, so I don't have the possibility to check everything. I'll have a new Mac to play with only next month :-)

Thanks!
Carlo

**Comment by ilpincy** [comment]
Great news! Thanks for the feedback! :-)

The permission problems you have might be because Homebrew works in /usr/local as a normal user, and in your tests you might have installed ARGoS manually through 'sudo make install'. In this case, the manual installation would create the ARGoS folders as root and cause this problem. I had it myself.

Cheers,
Carlo
