### ISSUE TITLE
make install fails: cannot find argos3/build/argos3.1.gz

### ISSUE THREAD

**Issue by daltonfury42** [ilpincy/homebrew-argos3#3]
I am trying to compile and install argos3 on an Arch Linux system. It got compiled fine, but the install recipe failed:

sudo make install 
[ 19%] Built target argos3core_simulator
[ 20%] Built target argos3
[ 22%] Built target argos3plugin_simulator_media
[ 29%] Built target argos3plugin_simulator_entities
[ 43%] Built target argos3plugin_simulator_qtopengl
[ 59%] Built target argos3plugin_simulator_dynamics2d
[ 61%] Built target argos3plugin_simulator_pointmass3d
[ 73%] Built target argos3plugin_simulator_genericrobot
[ 84%] Built target argos3plugin_simulator_footbot
[ 87%] Built target argos3plugin_simulator_eyebot
[ 89%] Built target argos3plugin_simulator_epuck
[ 91%] Built target argos3plugin_simulator_spiri
[ 91%] Built target test-client
[ 92%] Built target test-cylinder
[ 93%] Built target test-grid
[ 94%] Built target test-list
[ 95%] Built target test-range
[ 96%] Built target test-server
[ 96%] Built target test_eyebot_controller
[ 97%] Built target test_footbot_controller
[100%] Built target test_loop_functions
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/include/argos3/core/config.h
CMake Error at cmake_install.cmake:40 (file):
  file INSTALL cannot find "/home/fury/ARGoS/argos3/build/argos3.1.gz".

Makefile:105: recipe for target 'install' failed
make: **\* [install] Error 1

**Comment by ilpincy** [comment]
You need to run make doc before make install, as explained in the readme.

Also, if you're trying to install ARGoS from the sources on Arch, this is not the right project to report issues. This project is for the Mac OS X HomeBrew recipe to install ARGoS. Report your issue in the ARGoS github (https://github.com/ilpincy/argos3/issues/)
