### ISSUE TITLE
Can't run the simulation in mac

### ISSUE THREAD

**Issue by ARArun** [ilpincy/homebrew-argos3#6]
HI guys
I am very new to ARGoS. I installed argos in mac using brew as given in the instruction but when I tried to run some examples I faced these problems.
![screen shot 2017-06-02 at 2 10 26 pm](https://cloud.githubusercontent.com/assets/26450729/26718081/62760766-479d-11e7-84e9-93232e47c74c.png)

It would be really helpful if anybody could help me out.

Thanks in advance...

**Comment by ilpincy** [comment]
Hello, have you tried compiling the examples, following the instructions in the README?

**Comment by ARArun** [comment]
Thanks for replying so fast sir. I just did that and solved the issue. I did create the build file and compile it and it ran well. Thanks  a lot
![screen shot 2017-06-02 at 2 28 57 pm](https://cloud.githubusercontent.com/assets/26450729/26718738/99ce5f22-479f-11e7-9a25-d74d52ac1d33.png)
